### PR TITLE
Opt in to showing build summary

### PR DESCRIPTION
**Pull request by bgrainger**

### CODE REVIEW

**Comment by ejball** [comment]
IMO, this should be an option to opt *out* of the build summary.

**Comment by bgrainger** [comment]
I discussed and rejected that in #10; can we keep discussion there?

**Comment by ejball** [comment]
Per that discussion, I'd be fine with just turning off the summary with no option, or with a false-by-default `DotNetBuildSettings.ShowSummary`. I don't think we need to force a command-line option on everyone.

**Comment by ejball** [comment]
Fixed in 5.6.0.

**Pull request closed without merging**
